// File: src/engine/GameManager.js
// Description: Master State Manager. Acts as the bridge between the UI and the underlying game engines.

import { WORLD } from '../data/GameWorld.js';
import { initializeNewPlayer } from './ENGINE_PlayerCreation.js';
import { executeTravel } from './ENGINE_World_Travel.js';
import { executeEndMonth } from './ENGINE_Time_Loop.js';
import { executeRandomEvent } from './ENGINE_Events.js';
import { processCombatTurn } from './ENGINE_Combat_Loop.js';
import { generateCombatLoot } from './ENGINE_Loot_Drop.js';
import { executeInteraction } from './ENGINE_Interaction.js';
import {
	equipItem,
	unequipItem,
	dropItem,
	slaughterAnimal,
	recalculateEncumbrance,
} from './ENGINE_Inventory.js';
import {
	executeBuyTransaction,
	executeSellTransaction,
	executeRepairTransaction,
} from './ENGINE_Economy_Shops.js';
import { populatePOI } from './ENGINE_Spawner.js';
import { DB_LOCATIONS_POIS_Untamed } from '../data/DB_Locations_POIS.js';

export class GameManager {
	constructor() {
		this.gameState = {
			player: null,
			time: null,
			location: {
				currentWorldId: null,
				currentPoiId: null,
			},
			// Holds active NPCs in the current location generated by the Spawner
			activeEntities: [],
			// View Routing State
			currentView: 'VIEWPORT', // Options: 'VIEWPORT', 'COMBAT', 'TRADE'
			activeTargetId: null,
			activeTradeTag: null, // Stores the entityId of the NPC currently being engaged
		};
	}

	// ========================================================================
	// INITIALIZATION
	// ========================================================================

	/**
	 * Bootstraps a new game instance.
	 * @param {Object} creationParams - Name, age, patronGod, religion.
	 * @param {String} startingLocationId - The World_ID where the player spawns.
	 */
	startNewGame(creationParams, startingLocationId) {
		this.gameState.player = initializeNewPlayer(creationParams);

		this.gameState.time = {
			currentMonth: WORLD.TIME.startMonth,
			currentYear: 1250, // Arbitrary starting year
			totalMonthsPassed: 0,
			activeSeason: 'spring', // Will be synced dynamically later
		};

		this.gameState.location.currentWorldId = startingLocationId;
		this.gameState.location.currentPoiId = null;
		this.gameState.currentView = 'VIEWPORT';
		this.gameState.activeTargetId = null;

		// Note: UI should refresh and render the main game screen after this returns true
		return true;
	}

	// ========================================================================
	// TIME & TRAVEL ACTIONS
	// ========================================================================

	processAction_Travel(targetNodeId) {
		// 1. Execute Travel Logistics
		const travelResult = executeTravel(
			this.gameState.player,
			this.gameState.location.currentWorldId,
			targetNodeId,
			0, // Season modifier placeholder, logic can be imported from formulas later
		);

		if (travelResult.status !== 'SUCCESS') {
			return travelResult; // Return error payload to UI (e.g., FAILED_INSUFFICIENT_AP)
		}

		this.gameState.player = travelResult.updatedPlayer;
		this.gameState.location.currentWorldId = targetNodeId;

		// Reset view states upon moving to a new zone
		this.gameState.currentView = 'VIEWPORT';
		this.gameState.activeTargetId = null;
        this.gameState.activeTradeTag = null;

		// 2. Trigger Travel Event
		const eventResult = executeRandomEvent(this.gameState.player, 'travel');
		this.gameState.player = eventResult.updatedPlayer;

		return {
			status: 'SUCCESS',
			travelLog: travelResult,
			eventLog: eventResult.eventApplied,
		};
	}

	processAction_EndMonth() {
		// 1. Execute Time Progression & Logistics
		const timeResult = executeEndMonth(
			this.gameState.player,
			this.gameState.time,
		);

		if (timeResult.status === 'PERMADEATH') {
			this.gameState.player = timeResult.updatedPlayer;
			this.gameState.time = timeResult.updatedTime;
			return timeResult; // UI must render Game Over screen
		}

		this.gameState.player = timeResult.updatedPlayer;
		this.gameState.time = timeResult.updatedTime;

		// 2. Trigger Monthly Event
		const eventResult = executeRandomEvent(this.gameState.player, 'monthly');
		this.gameState.player = eventResult.updatedPlayer;

		if (eventResult.status === 'PERMADEATH') {
			return eventResult; // UI must render Game Over screen
		}

		// 3. Trigger World Refresh (Placeholder for Spawner Engine)
		// this.refreshWorldState();

		return {
			status: 'SUCCESS',
			timeLog: timeResult,
			eventLog: eventResult.eventApplied,
		};
	}

	// ========================================================================
	// COMBAT ACTIONS
	// ========================================================================

	processAction_CombatTurn(npcEntity, combatType, playerAction) {
		const turnResult = processCombatTurn(
			this.gameState.player,
			npcEntity,
			combatType,
			playerAction,
		);

		this.gameState.player = turnResult.playerEntity;

		// If combat is finished, process loot
		let lootPayload = null;
		if (turnResult.combatStatus !== 'CONTINUE') {
			lootPayload = generateCombatLoot(
				turnResult.npcEntity,
				combatType,
				turnResult.combatStatus,
			);

			// Auto-inject numeric loot into player inventory
			if (lootPayload.silverCoins)
				this.gameState.player.inventory.silverCoins +=
					lootPayload.silverCoins;
			if (lootPayload.food)
				this.gameState.player.inventory.food += lootPayload.food;

			// Physical items (tradeItems, equipment) remain in the payload for the UI to display in a "Loot Screen"
			// The UI will then call an inventory transfer function to claim them.

			// Reset interaction target post-combat
			this.gameState.activeTargetId = null;
			this.gameState.currentView = 'VIEWPORT';
		}

		return {
			combatStatus: turnResult.combatStatus,
			log: turnResult.log,
			loot: lootPayload,
		};
	}

	// ========================================================================
	// INTERACTION & INVENTORY ACTIONS
	// ========================================================================

	processAction_Interaction(actionTag, targetId, regionalExchangeRate = 10) {
		const result = executeInteraction(
			this.gameState.player,
			actionTag,
			targetId,
			regionalExchangeRate,
		);

		if (result.status === 'SUCCESS') {
			this.gameState.player = result.updatedPlayer;
		} else if (result.status === 'TRIGGER_COMBAT') {
			this.gameState.player = result.updatedPlayer;
			this.gameState.currentView = 'COMBAT';
			this.gameState.activeTargetId = result.targetId;
		} else if (result.status === 'TRIGGER_TRADE') {
			this.gameState.player = result.updatedPlayer;
			this.gameState.currentView = 'TRADE';
			this.gameState.activeTargetId = result.targetId;
			this.gameState.activeTradeTag = actionTag; // NOU
		}

		return result;
	}

	processAction_Equip(inventoryIndex, itemCategory) {
		const result = equipItem(
			this.gameState.player,
			inventoryIndex,
			itemCategory,
		);
		if (result.status === 'SUCCESS') {
			this.gameState.player = result.updatedPlayer;
		}
		return result;
	}

	processAction_Unequip(itemCategory) {
		const result = unequipItem(this.gameState.player, itemCategory);
		if (result.status === 'SUCCESS') {
			this.gameState.player = result.updatedPlayer;
		}
		return result;
	}

	processAction_DropItem(inventoryIndex, targetArrayName) {
		const result = dropItem(
			this.gameState.player,
			inventoryIndex,
			targetArrayName,
		);
		if (result.status === 'SUCCESS') {
			this.gameState.player = result.updatedPlayer;
		}
		return result;
	}

	processAction_SlaughterAnimal(inventoryIndex) {
		const result = slaughterAnimal(this.gameState.player, inventoryIndex);
		if (result.status === 'SUCCESS') {
			this.gameState.player = result.updatedPlayer;
		}
		return result;
	}

	processAction_RecalculateEncumbrance() {
		if (!this.gameState || !this.gameState.player) {
			return { status: 'FAILED_NO_PLAYER' };
		}

		const updatedPlayer = recalculateEncumbrance(this.gameState.player);
		this.gameState.player = updatedPlayer;

		return { status: 'SUCCESS', updatedPlayer: this.gameState.player };
	}

	// ========================================================================
	// COMMERCE ACTIONS
	// ========================================================================

	processAction_Commerce(transactionType, payload) {
		// payload expects: { itemDef, quantity, regionalExchangeRate, targetCategory, physicalItemIndex }
		let result;

		if (transactionType === 'BUY') {
			result = executeBuyTransaction(
				this.gameState.player,
				payload.itemDef,
				payload.quantity,
				payload.regionalExchangeRate,
				payload.targetCategory,
			);
		} else if (transactionType === 'SELL') {
			result = executeSellTransaction(
				this.gameState.player,
				payload.itemDef,
				payload.quantity,
				payload.regionalExchangeRate,
				payload.targetCategory,
				payload.physicalItemIndex,
			);
		} else if (transactionType === 'REPAIR') {
			result = executeRepairTransaction(
				this.gameState.player,
				payload.regionalExchangeRate,
				payload.targetCategory,
				payload.physicalItemIndex,
			);
		}

		if (result && result.status === 'SUCCESS') {
			this.gameState.player = result.updatedPlayer;
		}

		return result;
	}

	// ========================================================================
	// POI NAVIGATION & SPAWNING
	// ========================================================================

	processAction_EnterPoi(
		poiId,
		poiCategory = 'CIVILIZED',
		overrideApCost = null,
	) {
		let apCost = 0;

		// 1. Calculate dynamic cost with fallbacks
		if (overrideApCost !== null) {
			apCost = overrideApCost;
		} else if (poiCategory === 'CIVILIZED') {
			apCost =
				WORLD.SPATIAL?.actionCosts?.enterCivilizedPoiAp !== undefined
					? WORLD.SPATIAL.actionCosts.enterCivilizedPoiAp
					: 1;
		} else if (poiCategory === 'UNTAMED') {
			const poiData = DB_LOCATIONS_POIS_Untamed[poiId];
			apCost =
				poiData?.classification?.enterUntamedPoiApCost !== undefined
					? poiData.classification.enterUntamedPoiApCost
					: WORLD.SPATIAL?.actionCosts?.enterUntamedPoiApDefault || 1;
		}

		// 2. Validate AP
		if (this.gameState.player.progression.actionPoints < apCost) {
			return { status: 'FAILED_INSUFFICIENT_AP', requiredAp: apCost };
		}

		// 3. Mutate State
		this.gameState.player.progression.actionPoints -= apCost;
		this.gameState.location.currentPoiId = poiId;
		this.gameState.activeEntities = populatePOI(poiId, poiCategory);

		// Reset sub-views upon entering a POI
		this.gameState.currentView = 'VIEWPORT';
		this.gameState.activeTargetId = null;

		return {
			status: 'SUCCESS',
			activeEntities: this.gameState.activeEntities,
			apConsumed: apCost,
		};
	}

	processAction_ExploreUntamed() {
		// Read exploration cost with fallback
		const exploreCost =
			WORLD.SPATIAL?.actionCosts?.exploreUntamedAp !== undefined
				? WORLD.SPATIAL.actionCosts.exploreUntamedAp
				: 1;

		if (this.gameState.player.progression.actionPoints < exploreCost) {
			return { status: 'FAILED_INSUFFICIENT_AP', requiredAp: exploreCost };
		}

		// Deduct AP immediately
		this.gameState.player.progression.actionPoints -= exploreCost;

		const untamedKeys = Object.keys(DB_LOCATIONS_POIS_Untamed);
		if (untamedKeys.length === 0) return { status: 'FAILED_NO_POIS' };

		// Calculate total weight for proportional extraction
		let totalWeight = 0;
		const pool = [];
		for (const key of untamedKeys) {
			const poi = DB_LOCATIONS_POIS_Untamed[key];
			const chance = poi.classification?.locationSpawnChance || 10;
			totalWeight += chance;
			pool.push({ id: key, chance });
		}

		// Add probability of finding nothing (e.g., 30% of total weight sum)
		const nothingChance = Math.floor(totalWeight * 0.3);
		totalWeight += nothingChance;
		pool.push({ id: 'NOTHING', chance: nothingChance });

		let roll = Math.random() * totalWeight;
		let selectedPoiId = 'NOTHING';

		for (const item of pool) {
			roll -= item.chance;
			if (roll <= 0) {
				selectedPoiId = item.id;
				break;
			}
		}

		// Prepare event for UI, without mutating location state yet
		let eventLog;
		if (selectedPoiId === 'NOTHING') {
			eventLog = {
				title: 'Wilderness Exploration',
				description:
					'You scoured the area but found nothing of interest. Just empty wilderness.',
				changes: [{ label: 'Action Points', value: -exploreCost }],
				type: 'EXPLORE_NOTHING',
			};
		} else {
			const poiName = selectedPoiId.replace(/_/g, ' ');
			eventLog = {
				title: 'Location Discovered',
				description: `Through the dense wilderness, you stumbled upon a ${poiName}. Do you wish to approach it?`,
				changes: [{ label: 'Action Points', value: -exploreCost }],
				type: 'EXPLORE_SUCCESS',
				discoveredPoi: selectedPoiId,
			};
		}

		return { status: 'SUCCESS', eventLog };
	}

	processAction_ExitPoi() {
		this.gameState.location.currentPoiId = null;
		this.gameState.activeEntities = [];
		this.gameState.currentView = 'VIEWPORT';
		this.gameState.activeTargetId = null;
        this.gameState.activeTradeTag = null;
		return { status: 'SUCCESS' };
	}
}

// Instantiate a singleton to be used across the UI components
export const MasterGameManager = new GameManager();
