// File: src/engine/GameManager.js
// Description: Master State Manager. Acts as the bridge between the UI and the underlying game engines.

import { WORLD } from '../data/GameWorld.js';
import { initializeNewPlayer } from './ENGINE_PlayerCreation.js';
import { executeTravel } from './ENGINE_World_Travel.js';
import { executeEndMonth } from './ENGINE_Time_Loop.js';
import { executeRandomEvent } from './ENGINE_Events.js';
import { processCombatTurn } from './ENGINE_Combat_Loop.js';
import { generateCombatLoot } from './ENGINE_Loot_Drop.js';
import { executeInteraction } from './ENGINE_Interaction.js';
import { equipItem, unequipItem, dropItem, slaughterAnimal, recalculateEncumbrance } from './ENGINE_Inventory.js';
import { executeBuyTransaction, executeSellTransaction, executeRepairTransaction } from './ENGINE_Economy_Shops.js';

export class GameManager {
    constructor() {
        this.gameState = {
            player: null,
            time: null,
            location: {
                currentWorldId: null,
                currentPoiId: null
            },
            // Holds active NPCs in the current location generated by the Spawner
            activeEntities: [] 
        };
    }

    // ========================================================================
    // INITIALIZATION
    // ========================================================================

    /**
     * Bootstraps a new game instance.
     * @param {Object} creationParams - Name, age, patronGod, religion.
     * @param {String} startingLocationId - The World_ID where the player spawns.
     */
    startNewGame(creationParams, startingLocationId) {
        this.gameState.player = initializeNewPlayer(creationParams);
        
        this.gameState.time = {
            currentMonth: WORLD.TIME.startMonth,
            currentYear: 1250, // Arbitrary starting year
            totalMonthsPassed: 0,
            activeSeason: 'spring' // Will be synced dynamically later
        };

        this.gameState.location.currentWorldId = startingLocationId;
        this.gameState.location.currentPoiId = null;

        // Note: UI should refresh and render the main game screen after this returns true
        return true; 
    }

    // ========================================================================
    // TIME & TRAVEL ACTIONS
    // ========================================================================

    processAction_Travel(targetNodeId) {
        // 1. Execute Travel Logistics
        const travelResult = executeTravel(
            this.gameState.player, 
            this.gameState.location.currentWorldId, 
            targetNodeId, 
            0 // Season modifier placeholder, logic can be imported from formulas later
        );

        if (travelResult.status !== 'SUCCESS') {
            return travelResult; // Return error payload to UI (e.g., FAILED_INSUFFICIENT_AP)
        }

        this.gameState.player = travelResult.updatedPlayer;
        this.gameState.location.currentWorldId = targetNodeId;

        // 2. Trigger Travel Event
        const eventResult = executeRandomEvent(this.gameState.player, 'travel');
        this.gameState.player = eventResult.updatedPlayer;

        return {
            status: 'SUCCESS',
            travelLog: travelResult,
            eventLog: eventResult.eventApplied
        };
    }

    processAction_EndMonth() {
        // 1. Execute Time Progression & Logistics
        const timeResult = executeEndMonth(this.gameState.player, this.gameState.time);
        
        if (timeResult.status === 'PERMADEATH') {
            this.gameState.player = timeResult.updatedPlayer;
            this.gameState.time = timeResult.updatedTime;
            return timeResult; // UI must render Game Over screen
        }

        this.gameState.player = timeResult.updatedPlayer;
        this.gameState.time = timeResult.updatedTime;

        // 2. Trigger Monthly Event
        const eventResult = executeRandomEvent(this.gameState.player, 'monthly');
        this.gameState.player = eventResult.updatedPlayer;

        if (eventResult.status === 'PERMADEATH') {
            return eventResult; // UI must render Game Over screen
        }

        // 3. Trigger World Refresh (Placeholder for Spawner Engine)
        // this.refreshWorldState();

        return {
            status: 'SUCCESS',
            timeLog: timeResult,
            eventLog: eventResult.eventApplied
        };
    }

    // ========================================================================
    // COMBAT ACTIONS
    // ========================================================================

    processAction_CombatTurn(npcEntity, combatType, playerAction) {
        const turnResult = processCombatTurn(this.gameState.player, npcEntity, combatType, playerAction);
        
        this.gameState.player = turnResult.playerEntity;
        
        // If combat is finished, process loot
        let lootPayload = null;
        if (turnResult.combatStatus !== 'CONTINUE') {
            lootPayload = generateCombatLoot(turnResult.npcEntity, combatType, turnResult.combatStatus);
            
            // Auto-inject numeric loot into player inventory
            if (lootPayload.silverCoins) this.gameState.player.inventory.silverCoins += lootPayload.silverCoins;
            if (lootPayload.food) this.gameState.player.inventory.food += lootPayload.food;
            
            // Physical items (tradeItems, equipment) remain in the payload for the UI to display in a "Loot Screen"
            // The UI will then call an inventory transfer function to claim them.
        }

        return {
            combatStatus: turnResult.combatStatus,
            log: turnResult.log,
            loot: lootPayload
        };
    }

    // ========================================================================
    // INTERACTION & INVENTORY ACTIONS
    // ========================================================================

    processAction_Interaction(actionTag, regionalExchangeRate) {
        const result = executeInteraction(this.gameState.player, actionTag, regionalExchangeRate);
        if (result.status === 'SUCCESS') {
            this.gameState.player = result.updatedPlayer;
        }
        return result;
    }

    processAction_Equip(inventoryIndex, itemCategory) {
        const result = equipItem(this.gameState.player, inventoryIndex, itemCategory);
        if (result.status === 'SUCCESS') {
            this.gameState.player = result.updatedPlayer;
        }
        return result;
    }

    processAction_Unequip(itemCategory) {
        const result = unequipItem(this.gameState.player, itemCategory);
        if (result.status === 'SUCCESS') {
            this.gameState.player = result.updatedPlayer;
        }
        return result;
    }

    processAction_DropItem(inventoryIndex, targetArrayName) {
        const result = dropItem(this.gameState.player, inventoryIndex, targetArrayName);
        if (result.status === 'SUCCESS') {
            this.gameState.player = result.updatedPlayer;
        }
        return result;
    }

    processAction_SlaughterAnimal(inventoryIndex) {
        const result = slaughterAnimal(this.gameState.player, inventoryIndex);
        if (result.status === 'SUCCESS') {
            this.gameState.player = result.updatedPlayer;
        }
        return result;
    }

    processAction_RecalculateEncumbrance() {
        if (!this.gameState || !this.gameState.player) {
            return { status: 'FAILED_NO_PLAYER' };
        }
        
        const updatedPlayer = recalculateEncumbrance(this.gameState.player);
        this.gameState.player = updatedPlayer;
        
        return { status: 'SUCCESS', updatedPlayer: this.gameState.player };
    }

    // ========================================================================
    // COMMERCE ACTIONS
    // ========================================================================

    processAction_Commerce(transactionType, payload) {
        // payload expects: { itemDef, quantity, regionalExchangeRate, targetCategory, physicalItemIndex }
        let result;

        if (transactionType === 'BUY') {
            result = executeBuyTransaction(this.gameState.player, payload.itemDef, payload.quantity, payload.regionalExchangeRate, payload.targetCategory);
        } else if (transactionType === 'SELL') {
            result = executeSellTransaction(this.gameState.player, payload.itemDef, payload.quantity, payload.regionalExchangeRate, payload.targetCategory, payload.physicalItemIndex);
        } else if (transactionType === 'REPAIR') {
            result = executeRepairTransaction(this.gameState.player, payload.regionalExchangeRate, payload.targetCategory, payload.physicalItemIndex);
        }

        if (result && result.status === 'SUCCESS') {
            this.gameState.player = result.updatedPlayer;
        }

        return result;
    }
}

// Instantiate a singleton to be used across the UI components
export const MasterGameManager = new GameManager();